name: CI Процесс

on:
  push:
    branches:
      - main
      - develop
      - release/*
  pull_request:
    branches:
      - main
      - develop
      - release/*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: JDK 23 тохируулах
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven

      - name: Checkstyle шалгах
        run: mvn checkstyle:check

      - name: Тест ба JaCoCo Coverage шалгах
        run: mvn test jacoco:check

      - name: JaCoCo тайлан үүсгэх
        run: mvn jacoco:report

      - name: JaCoCo тайланг upload хийх
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/
